# Generated by Django 4.2.16 on 2024-09-30 07:31

import creator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_image_url', models.ImageField(upload_to=creator.models.profile_image_uplaod_to)),
                ('logo_url', models.ImageField(null=True, upload_to=creator.models.logo_url_uplaod_to)),
                ('bio', models.TextField(null=True)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('contry', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('phon', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
